### ISSUE TITLE
java.lang.NullPointerException when reporting patient with temporary CPR

### ISSUE THREAD

**Issue by JacobBangSSE** [scandihealth/lpr3-docs#143]
**This issue is blocking**

We gets the following error from:
https://lprws-test.sds.dsdn.dk/cda-ws/DocumentRepository_Service/PatientHealthcareReportingService

```xml
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
   <env:Header xmlns:env="http://www.w3.org/2003/05/soap-envelope"/>
   <soap:Body>
      <soap:Fault>
         <soap:Code>
            <soap:Value>soap:Receiver</soap:Value>
         </soap:Code>
         <soap:Reason>
            <soap:Text xml:lang="en">java.lang.NullPointerException</soap:Text>
         </soap:Reason>
      </soap:Fault>
   </soap:Body>
</soap:Envelope>
```

I have attached the CDA document here we are trying to report:
[cda_eoc_erst_pat_error.txt](https://github.com/scandihealth/lpr3-docs/files/2132750/cda_eoc_erst_pat_error.txt)

**Comment by JacobBangSSE** [comment]
I can see we have some schematron validation errors:
```
    Text: dtr1-1-II: @root is required if @nullFlavor is not present
    Test: @nullFlavor or (not(@nullFlavor) and @root)
    See:
    Location: /*:ClinicalDocument[namespace-uri()='urn:hl7-org:v3'][1]/*:recordTarget[namespace-uri()='urn:hl7-org:v3'][1]/*:patientRole[namespace-uri()='urn:hl7-org:v3'][1]/*:id[namespace-uri()='urn:hl7-org:v3'][1]

    Text: (DKAlternativelyIdentifiedPatientRoleBody): attribute @root SHALL be present.
    Test: @root
    See:
    Location: /*:ClinicalDocument[namespace-uri()='urn:hl7-org:v3'][1]/*:recordTarget[namespace-uri()='urn:hl7-org:v3'][1]/*:patientRole[namespace-uri()='urn:hl7-org:v3'][1]/*:id[namespace-uri()='urn:hl7-org:v3'][1]
```
I close this issue. Please note that we think that returning java.lang.NullPointerException is completely useless when trying to develop against a test service.
