### ISSUE TITLE
Error in schematron validation logic: DKEpisodeOfCareSummariesDocument 

### ISSUE THREAD

**Issue by RolandPedersenSSE** [scandihealth/lpr3-docs#65]
There is an error in the schematron validation logic in relation to ClinicalDocument/id root for DKEpisodeOfCareSummariesDocument.

The error message states that **The value of @root must be the same as /setId/@root** but still fails if the rule is followed.
The test states that: **@root != /setId/@root** which is in direct contrast with the error message

The error appears both if the values are equal and when they are different

Art-decor: [DK Episode Of Care Summaries Document](http://art-decor.org/art-decor/decor-templates--lpr-?id=1.2.208.176.7.1.10.95&effectiveDate=dynamic)
Test output
```
    Text: (DKEpisodeOfCareSummariesDocument): The value of @root must be the same as /setId/@root
    Test: @root != /setId/@root
    See:
    Location: /*:ClinicalDocument/*:id
```

Example:
```
<id root="c1dee9f6-ef9d-452d-a4b3-ec358f550826" 
    extension="7cb8dde4-8a2b-43f4-978b-0c92c7b2023a"/>
<setId assigningAuthorityName="Region Midtjylland" 
    root="c1dee9f6-ef9d-452d-a4b3-ec358f550826"/>
```
