### ISSUE TITLE
Error in schematron validation logic: DKRelatedDocument id

### ISSUE THREAD

**Issue by RolandPedersenSSE** [scandihealth/lpr3-docs#66]
There is an error in the schematron validation logic in relation to /*:ClinicalDocument/*:relatedDocument/*:parentDocument/*:id for DKRelatedDocument.

The error message states that **The value of @root must be the same as /setId/@root** but still fails if the rule is followed.
The test states that: **@root != /setId/@root** which is in direct contrast with the error message

The error appears both if the values are equal and when they are different

Art-decor: [DK RelatedDocument](http://art-decor.org/art-decor/decor-templates--lpr-?id=1.2.208.176.7.1.10.111&effectiveDate=2017-11-11T00:00:00)
Test output
```
    Text: (DK RelatedDocument): The value of @root must be the same as /setId/@root
    Test: @root != /setId/@root
    See:
    Location: /*:ClinicalDocument/*:id
```

Example:

```xml
<setId assigningAuthorityName="Region Midtjylland" 
    root="c1dee9f6-ef9d-452d-a4b3-ec358f550826"/>
...
<relatedDocument typeCode="APND">
	<parentDocument classCode="DOCCLIN" moodCode="EVN">
		<id root="c1dee9f6-ef9d-452d-a4b3-ec358f550826" extension="0fdd1ae4-939e-44d2-9f40-79b6e18ea94a"/> 
		<setId root="c1dee9f6-ef9d-452d-a4b3-ec358f550826"/>
		<versionNumber value="2"/>
	</parentDocument>
</relatedDocument>

```
