### ISSUE TITLE
Error in schematron validation logic: DKEpisodeOfCareAct id

### ISSUE THREAD

**Issue by RolandPedersenSSE** [scandihealth/lpr3-docs#68]
There is an error in the schematron validation logic in relation to /*:ClinicalDocument/*:component/*:structuredBody/*:component/*:section/*:entry/*:act/*:id for DKEpisodeOfCareAct .

The error message states that **The value of @root must be the same as /setId/@root** but still fails if the rule is followed.
The test states that: **@root != /setId/@root** which is in direct contrast with the error message

The error appears both if the values are equal and when they are different

Art-decor: [DK Episode Of Care Act](http://art-decor.org/art-decor/decor-templates--lpr-?id=1.2.208.176.7.1.10.80&effectiveDate=2017-11-11T00:00:00)
Test output
```
    Text: (DKEpisodeOfCareAct): The value of @root must be the same as /setId/@root
    Test: @root != /setId/@root
    See:
    Location: /*:ClinicalDocument/*:component/*:structuredBody/*:component/*:section/*:entry/*:act/*:id
```

Example:
```xml
<setId assigningAuthorityName="Region Midtjylland" 
    root="c1dee9f6-ef9d-452d-a4b3-ec358f550826"/>
...
<act classCode="PCPR" moodCode="EVN">
	<templateId root="1.2.208.176.7.1.10.80"/>
	<templateId root="2.16.840.1.113883.10.12.301"/>
	<id extension="a6750254-6557-476f-b038-06b5d6d0b2e1" 
		root="c1dee9f6-ef9d-452d-a4b3-ec358f550826"/>
...
```
