### ISSUE TITLE
Error in schematron validation logic: DK Alternatively Identified Patient Role (Body) id

### ISSUE THREAD

**Issue by RolandPedersenSSE** [scandihealth/lpr3-docs#69]
There is an error in the schematron validation logic in relation to /*:ClinicalDocument/*:component/*:structuredBody/*:component/*:section/*:entry/*:act/*:id for DK Alternatively Identified Patient Role (Body).

The error message states that **Attribute @root SHALL be of data type 'uid'** but it does not fit with the example given on art-decor:
```xml
<!--ErstatningsCPRnummer Region Nordjylland-->
<id root="6071000016008" 
      extension="08119675AG1" 
      assigningAuthorityName="Region Nordjylland"/>
```

Art-decor: [Alternatively Identified Patient Role (Body)](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?id=1.2.208.176.7.1.10.132&effectiveDate=dynamic)
Test output
```
    Text: (DKAlternativelyIdentifiedPatientRoleBody): Attribute @root SHALL be of data type 'uid'
    Test: not(@root) or matches(@root,'^[0-2](\.(0|[1-9]\d*))*$') or matches(@root,'^[A-Fa-f\d]8-[A-Fa-f\d]4-[A-Fa-f\d]4-[A-Fa-f\d]4-[A-Fa-f\d]12$') or matches(@root,'^[A-Za-z][A-Za-z\d\-]*$')
    See:
    Location: /*:ClinicalDocument[1]/*:recordTarget[1]/*:patientRole[1]/*:id[1] 

    Text: dtr1-10-II: @root SHALL be a syntactically correct OID, UUID.
    Test: not(@root) or matches(@root, $OIDpattern) or matches(@root, $UUIDpattern)
    See:
    Location: /*:ClinicalDocument[1]/*:recordTarget[1]/*:patientRole[1]/*:id[1]

```

Example:
```xml
<recordTarget>
        <templateId root="1.2.208.176.7.1.10.101"/>
        <templateId root="2.16.840.1.113883.10.12.101"/>
        <patientRole classCode="PAT">
            <templateId root="1.2.208.176.7.1.10.107"/>
            <id root="6081000016005" extension="0101010101" assigningAuthorityName="Region Midtjylland"/>
            <addr>
...
```
